#!/bin/sh
if [ "$#" -ne 1 ]; then
	echo usage: impermanence [-v] user
	exit 2
fi

if [ "$(id -u)" -eq 0 -a "$(id -u $1)" -ne 0 ]; then
	echo hi
	su "$1" /usr/local/bin/impermanence "$1"
	exit $?
fi

while read -r line
do
	if [ -z "${line}" ]; then
		continue
	fi

	from="/home/persist/$1/${line}"
	to="/home/$1/${line}"

	mkdir -p "$(dirname "${to}")" || exit 1
	ln -s "${from}" "${to}" || exit 1
done < "/home/persist/$1/impermanence"
