#!/bin/sh

KEY="${HOME}/.passes/meta/identities"
PASSDIR="${HOME}/.passes"

prompt() {
	stty -echo
	printf "Enter a password: "
	read first
	printf '\n'
	printf "Re-enter the password: "
	read second
	printf '\n'
	stty echo
	if [ "$first" != "$second" ]; then
		echo "Passwords do not match." 1>&2
		return 1
	fi
	ENTERED="$first"
	return 0
}

add() {
	while getopts m name
	do
		case $name in
		m) noprompt=0 ;;
		?)
			echo "usage: pass add [-m] <password>"; exit 2 ;;
		esac
	done
	shift $(($OPTIND - 1))

	if [ $# -ne 1 ]; then
		echo "usage: pass add [-m] <password>"
		exit 2
	fi

	if [ -z $noprompt ]; then
		prompt 
	else
		ENTERED=$(cat)
	fi

	if [ $? != 0 ]; then
		exit 1
	fi
	mkdir -p "${PASSDIR}/$(dirname $1)"
	echo $ENTERED | age -R "${PASSDIR}/meta/recipients" -i "$KEY" -e -o "${PASSDIR}/passwords/$1"
}

get() {
	if [ $# -ne 1 ]; then
		echo "usage: pass get <password>"
		exit 2
	fi
	if [ ! -f "${PASSDIR}/passwords/$1" ]; then
		echo "No such password found" 2>&1
		exit 1
	fi
	age -i "$KEY" -d "${PASSDIR}/passwords/$1"
}

case "$1"
in
	add)
		shift 1
		add $@ ;;
	get)
		shift 1
		get $@;;
	"")     echo "usage: pass [command] <password>";;
	*) get $@ ;;
esac
